django_tutorial/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
from __future__ import unicode_literals

import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.text

polls/views.py
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'question_list'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if request.method == 'POST':
        choice_list = dict(request.POST.iterlists()).get('choice')
        if choice_list:
            for choice in Choice.objects.filter(id__in=choice_list):
                choice.votes += 1
                choice.save()
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })

    return HttpResponseRedirect(reverse('polls:detail', args=(question.id,)))

polls/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Django-tutorial | {% block title %} {% endblock %}</title>

    {% block favicon %}
      <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}"/>
    {% endblock %}

    {# Block where global CSS will go. #}
    {% block styles %}
      <link href="{% static 'lib/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel='stylesheet' type='text/css'/>
      <link href='{% static "css/style.css" %}' rel='stylesheet' type='text/css'/>
    {% endblock %}

    {# Additional CSS - specific to certain pages #}
    {% block extrastyles %}{% endblock %}
  </head>

  <body>
  {# Main content goes in this 'layout' block #}
  <div class="container">
    {% block content %}{% endblock %}
  </div>


  {# Local scripts #}
  {% block scripts %}{% endblock %}

  {# Additional JS scripts #}
  {% block extrascripts %}{% endblock %}
  </body>
</html>

polls/templates/polls/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ question.id }} question-detail {% endblock %}

{% block content %}
  <h1>{{ question.text }}</h1>

  {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

  <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
      <div class="form-group">
        <div class="checkbox">
          <label for="choice{{ choice.id }}">
          <input type="checkbox" name="choice" id="choice{{ choice.id }}"
                 value="{{ choice.id }}"/>{{ choice.text }}
        </label></div>

      </div>
    {% endfor %}
    <button class="btn btn-default" type="submit">Vote</button>
  </form>
{% endblock content %}

polls/templates/polls/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}question-list {% endblock %}

{% block content %}
  {% if question_list %}
    <ul>
      {% for question in question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.text }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No polls are available.</p>
  {% endif %}
{% endblock content %}

polls/templates/polls/results.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ question.id }} question-result {% endblock %}

{% block content %}

  <h1>{{ question.text }}</h1>

  <ul>
    {% for choice in question.choice_set.all %}
      <li>{{ choice.text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
  </ul>

  <a href="{% url 'polls:detail' question.id %}">Vote again?</a>

{% endblock content %}